name: flutter_firebase
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.9.0

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
